/*********************************************************/
/** pdb file writer **************************************/
/** Updated for multi-molecules and for Avagadro display */
/** Nov. 2013 Dave Willock.                              */
/*********************************************************/

#include <stdio.h>
#include <math.h>
#include "maxima.h"
#include "constants.h"
#include "structures.h"

void write_pdb(FILE *pdb_fp, atom *guest_ptrs[], int num_guests,
               list_partition *p_guest_demarc, double *p_abc,
               int *p_super, double *p_latt_vec)
{
int iloop,  ineigh, neigh_index, tot_num, mult;
int ia, ib, ic, image, imol, num_atoms;
atom *p_atom;
double dx, dy, dz, dist;
double image_vec[3];

list_partition *p_demarc;

tot_num=0;
p_demarc= p_guest_demarc;
for (imol=0; imol< num_guests; imol++) 
  {
     tot_num= p_demarc->num;
     p_demarc++;
  }

mult=(*p_super)*(*(p_super+1))*(*(p_super+2));

fprintf(pdb_fp,"HEADER    Zebedde generated pdb file;    %d atoms\n",mult*tot_num);
fprintf(pdb_fp,"AUTHOR    Generated by ZEBEDDE\n");

fprintf(pdb_fp,"CRYST1   %6.3f   %6.3f  %6.3f %6.2f %6.2f %6.2f P1          1\n", *p_abc,
                     *(p_abc+1),*(p_abc+2),*(p_abc+3),
                                           *(p_abc+4),
                                           *(p_abc+5));

/***********************************************************/
/*** p_super points to an integer array defining the *******/
/*** extent of the required super cell               *******/
/***********************************************************/
 
image=0;
for ( ia = 0; ia <= *p_super-1; ia++ )
 {

   for ( ib = 0; ib <= *(p_super+1)-1 ; ib++ )
    {

      for ( ic = 0; ic <= *(p_super+2)-1; ic++ )
        {
          image_vec[0] =  ia * *p_latt_vec 
                         +ib * *(p_latt_vec+3)
                         +ic * *(p_latt_vec+6);

          image_vec[1] =  ia * *(p_latt_vec+1)
                         +ib * *(p_latt_vec+4)
                         +ic * *(p_latt_vec+7);

          image_vec[2] =  ia * *(p_latt_vec+2)
                         +ib * *(p_latt_vec+5)
                         +ic * *(p_latt_vec+8);

          p_demarc= p_guest_demarc;
          for (imol=0; imol< num_guests; imol++)
             {
               p_atom = guest_ptrs[imol];
               num_atoms= p_demarc->num;
//               printf("Write pdb for molecule %d with %d atoms\n",imol, num_atoms);

               for ( iloop=0; iloop <= p_demarc->end; iloop++)
                 {
    fprintf(pdb_fp,"ATOM   %4d %2s  LIG      1     %7.3f %7.3f %7.3f  1.00  0.00          %2s\n",
                                        iloop+1+image*num_atoms, p_atom->elem,
                                        p_atom->x + image_vec[0],
                                        p_atom->y + image_vec[1], 
                                        p_atom->z + image_vec[2],
                                        p_atom->elem);

                     p_atom++;
                 }
               p_demarc++;
             }
          image++;
        }
    }
 }

//image=0;
//for ( ia = 0; ia <= *p_super-1; ia++ )
// {
//
//   for ( ib = 0; ib <= *(p_super+1)-1 ; ib++ )
//    {
//
//      for ( ic = 0; ic <= *(p_super+2)-1; ic++ )
//        {
//           p_atom = p_molecule;
//           for ( iloop=0; iloop < num_atoms; iloop++)
//             {
//               fprintf(pdb_fp,"CONECT %4d", iloop+1+image*num_atoms);
//     
//               for ( ineigh=0; ineigh < p_atom->num_neigh; ineigh++)
//                 {
//                   neigh_index = p_atom->neighb[ineigh]; 
//
//                   dx = p_atom->x - (p_molecule+neigh_index)->x;
//                   dy = p_atom->y - (p_molecule+neigh_index)->y;
//                   dz = p_atom->z - (p_molecule+neigh_index)->z;
//
//                 dist = sqrt( dx*dx + dy*dy + dz * dz);
//
//                 if (dist < 3.0) fprintf(pdb_fp," %4d", 
//                                 neigh_index+1+image*num_atoms);
//               }
//
//             fprintf(pdb_fp,"\n");
//             p_atom++;
//          }
//        image++;
//      }
//   }
//}

fprintf(pdb_fp,"END\n");

return;
}

