/*********************************************************/
/** xyz file writer **************************************/
/** Updated for multi-molecules and for Avagadro display */
/** Nov. 2013 Dave Willock.                              */
/*********************************************************/

#include <stdio.h>
#include <math.h>
#include "maxima.h"
#include "constants.h"
#include "structures.h"

void write_xyz(FILE *xyz_fp, atom *guest_ptrs[], int num_guests,
               list_partition *p_guest_demarc, double *p_abc,
               int *p_super, double *p_latt_vec)
{
int iloop,  ineigh, neigh_index;
int ia, ib, ic, image, imol, num_atoms;
atom *p_atom;
double dx, dy, dz, dist;
double image_vec[3];

list_partition *p_demarc;

/**** Count up the total number of atoms ***/

num_atoms=0;
p_demarc=p_guest_demarc;
for (imol=0; imol<num_guests; imol++)
   {
      num_atoms += p_demarc->num;
      p_demarc++;
   }
               
fprintf(xyz_fp,"%10d\n", num_atoms);
fprintf(xyz_fp,"Generated by ZEBEDDE\n");

/***********************************************************/
/*** p_super points to an integer array defining the *******/
/*** extent of the required super cell               *******/
/***********************************************************/
 
image=0;
for ( ia = 0; ia <= *p_super-1; ia++ )
 {

   for ( ib = 0; ib <= *(p_super+1)-1 ; ib++ )
    {

      for ( ic = 0; ic <= *(p_super+2)-1; ic++ )
        {
          image_vec[0] =  ia * *p_latt_vec 
                         +ib * *(p_latt_vec+3)
                         +ic * *(p_latt_vec+6);

          image_vec[1] =  ia * *(p_latt_vec+1)
                         +ib * *(p_latt_vec+4)
                         +ic * *(p_latt_vec+7);

          image_vec[2] =  ia * *(p_latt_vec+2)
                         +ib * *(p_latt_vec+5)
                         +ic * *(p_latt_vec+8);

          p_demarc= p_guest_demarc;
          for (imol=0; imol< num_guests; imol++)
             {
               p_atom = guest_ptrs[imol];
               num_atoms= p_demarc->num;

               for ( iloop=0; iloop <= p_demarc->end; iloop++)
                 {
    fprintf(xyz_fp,"%s  %7.3f %7.3f %7.3f\n",
                                        p_atom->elem,
                                        p_atom->x + image_vec[0],
                                        p_atom->y + image_vec[1], 
                                        p_atom->z + image_vec[2]);

                     p_atom++;
                 }
               p_demarc++;
             }
          image++;
        }
    }
 }

//image=0;
//for ( ia = 0; ia <= *p_super-1; ia++ )
// {
//
//   for ( ib = 0; ib <= *(p_super+1)-1 ; ib++ )
//    {
//
//      for ( ic = 0; ic <= *(p_super+2)-1; ic++ )
//        {
//           p_atom = p_molecule;
//           for ( iloop=0; iloop < num_atoms; iloop++)
//             {
//               fprintf(xyz_fp,"CONECT %4d", iloop+1+image*num_atoms);
//     
//               for ( ineigh=0; ineigh < p_atom->num_neigh; ineigh++)
//                 {
//                   neigh_index = p_atom->neighb[ineigh]; 
//
//                   dx = p_atom->x - (p_molecule+neigh_index)->x;
//                   dy = p_atom->y - (p_molecule+neigh_index)->y;
//                   dz = p_atom->z - (p_molecule+neigh_index)->z;
//
//                 dist = sqrt( dx*dx + dy*dy + dz * dz);
//
//                 if (dist < 3.0) fprintf(xyz_fp," %4d", 
//                                 neigh_index+1+image*num_atoms);
//               }
//
//             fprintf(xyz_fp,"\n");
//             p_atom++;
//          }
//        image++;
//      }
//   }
//}


return;
}

